### ISSUE TITLE
Increase update frequency of energy consumption sensors

### ISSUE THREAD

**Issue by apranda** [ablyler/home-assistant-bradford-white-connect#20]
Would it be possible to increase the update frequency of the energy consumption sensors so that it updates every 3 hours like in the Bradford Connect app?

**Comment by ablyler** [comment]
@apranda, we could do that. I believe only a limited amount of data is available at this granularity.

**Comment by apranda** [comment]
> @apranda, we could do that. I believe only a limited amount of data is available at this granularity.

The app reports power consumption in 3 hour intervals so if possible it would be nice to have this same granularity rather than the one report at midnight that has the power consumption reported at once for the whole day.

**Comment by ablyler** [comment]
@apranda what are your thoughts on making it so that the energy sensor value would reset daily then? It looks like the API only returns about ~3 days’ worth of values when you ask for this level of granularity. On the plus side, it looks like the API is returning a datapoint for each hour.

Personally I am using ESPHome w/ [ESPSense](https://github.com/cbpowell/ESPSense) + [ESP32 Energy Meter Main Board](https://circuitsetup.us/product/expandable-6-channel-esp32-energy-meter/?v=0b3b97fa6688) + CT clamps to monitor the energy usage of my water heater in realtime.

**Comment by apranda** [comment]
> @apranda what are your thoughts on making it so that the energy sensor value would reset daily then? It looks like the API only returns about ~3 days’ worth of values when you ask for this level of granularity. On the plus side, it looks like the API is returning a datapoint for each hour.
> 
> Personally I am using ESPHome w/ [ESPSense](https://github.com/cbpowell/ESPSense) + [ESP32 Energy Meter Main Board](https://circuitsetup.us/product/expandable-6-channel-esp32-energy-meter/?v=0b3b97fa6688) + CT clamps to monitor the energy usage of my water heater in realtime.

I'm already using the energy sensor in the Energy dashboard to monitor the daily usage, therefore I would not have a problem with the sensor natively having a daily reset. It was more of a question if the API updates the value of the energy sensors more than once a day. Even 3-4x a day would be a usable improvement without running into any potential rate limits.

**Comment by ablyler** [comment]
Updated in v0.2.11
