### ISSUE TITLE
Energy Consumption going negative exactly 3 months after start

### ISSUE THREAD

**Issue by httr-1991** [ablyler/home-assistant-bradford-white-connect#21]
Original issue post, I probably put in the wrong project;
https://github.com/ablyler/bradford_white_connect_client/issues/45

First off, thank you for your contributions, I love this integration.

We installed the Bradford White Connect on April 17th. On July 17th, the total energy values being reported were lower than the previous day.

![image](https://github.com/user-attachments/assets/e6119b56-803b-4188-bc90-5145cda10122)

When capturing the delta for daily consumption, this shows negative energy being consumed.

![image](https://github.com/user-attachments/assets/c025c4cc-7d6a-4867-907d-8cd69e32eae8)

I'm thinking that the energy value being reported is only the last 90days or 3months worth. 

Is it possible to publish daily values instead of rolling 90 day totals?

**Comment by jeffstearns** [comment]
I see the same problem.  

I started collecting **heat_pump_energy_usage** data on 2024-05-20.

Data values increased as expected until 2024-07-16.  At that time, data collection stopped because my Bradford White account wasn't able to fetch any data.

Data collection resumed on 2024-08-13.  (Thus my energy usage between 2024-07-16 and 2024-08-13 is unknown.)

My **heat_pump_energy_usage** values have been _decreasing_ since 2024-08-13.

(I don't know the exact date when the values began decreasing because I don't have data during the time window from 2024-07-16 to 2024-08-13.)

It's interesting that my Bradford White data collection failed on the same day that httr-1991's data began going negative.  I don't know whether this is significant or a coincidence.

**Comment by httr-1991** [comment]
@jeffstearns - The date is just a conincidence because I was still getting data in the BW Connect app and my delta consumption can be positive when that days consumption is greater than the consumption of 90 days ago.

**Comment by ablyler** [comment]
Thank you for the report! It seems the API only provides energy information for the past three months. I’m pushing an update now that adjusts the add-on to report the current month’s data to Home Assistant. As a result, at the beginning of each month, you’ll see the energy information reset. The Energy Dashboard in Home Assistant should handle this transition smoothly and continue to provide accurate insights.
